#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DrinkWater.Resource", IsApplication=true)]

namespace DrinkWater
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AddCustomWaterButton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AddCustomWaterTextBox = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int AddPrevWaterButton = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int DrinkingProgressBar = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int GlassIcon_Water_Bottle_96 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int MAHeaderSummaryBox = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Plus_Math_60_Pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Plus_Math_60_Shadow = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Recurring_Icon_60_Pressed = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Recurring_Icon_60_Shadow = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050020
			public const int DrinkLogEditModal_CancelButton = 2131034144;
			
			// aapt resource value: 0x7f05001f
			public const int DrinkLogEditModal_UpdateButton = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int DrinkLogEditModal_input = 2131034142;
			
			// aapt resource value: 0x7f05001b
			public const int DrinkLogEditModal_text = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int EditLog_tableLayout1 = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int EditLog_tableRow1 = 2131034141;
			
			// aapt resource value: 0x7f050013
			public const int TodayDrinkLogGrid = 2131034131;
			
			// aapt resource value: 0x7f050022
			public const int TodayDrinkLogGridImage = 2131034146;
			
			// aapt resource value: 0x7f050021
			public const int TodayDrinkLogGridLinearLayout = 2131034145;
			
			// aapt resource value: 0x7f050023
			public const int TodayDrinkLogGridML = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int TodayDrinkLogGridTime = 2131034148;
			
			// aapt resource value: 0x7f050019
			public const int button_addCutomWater = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int button_addPrevWater = 2131034138;
			
			// aapt resource value: 0x7f050017
			public const int editText_customAddWater = 2131034135;
			
			// aapt resource value: 0x7f050012
			public const int frameLayout_middleMan = 2131034130;
			
			// aapt resource value: 0x7f05000c
			public const int progressBar_DrinkProgress = 2131034124;
			
			// aapt resource value: 0x7f050000
			public const int scroller = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int tableLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int tableLayout2 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int tableLayout3 = 2131034117;
			
			// aapt resource value: 0x7f05000d
			public const int tableLayout6 = 2131034125;
			
			// aapt resource value: 0x7f050015
			public const int tableLayout7 = 2131034133;
			
			// aapt resource value: 0x7f050002
			public const int tableRow1 = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int tableRow2 = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int tableRow3 = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int tableRow4 = 2131034123;
			
			// aapt resource value: 0x7f050011
			public const int tableRow5 = 2131034129;
			
			// aapt resource value: 0x7f05000e
			public const int tableRow7 = 2131034126;
			
			// aapt resource value: 0x7f050016
			public const int tableRow8 = 2131034134;
			
			// aapt resource value: 0x7f050010
			public const int textView_PercentTextPercent = 2131034128;
			
			// aapt resource value: 0x7f050007
			public const int textView_ProgressActualsML = 2131034119;
			
			// aapt resource value: 0x7f05000f
			public const int textView_ProgressPercent = 2131034127;
			
			// aapt resource value: 0x7f05000a
			public const int textView_ProgressTextML = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int textView_ProgressTextSlash = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int textView_TargetML = 2131034121;
			
			// aapt resource value: 0x7f050018
			public const int textView_customAddTextML = 2131034136;
			
			// aapt resource value: 0x7f050014
			public const int textView_defaultTextBeforeAdd = 2131034132;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int TodayDrinkLogEditModal = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TodayDrinkLogGridElement = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
